sonar.projectKey=awali-contracts
sonar.projectName=AWALI Smart Contracts
sonar.sources=contracts
sonar.tests=test
sonar.exclusions=**/node_modules/**,**/artifacts/**,**/cache/**
sonar.sourceEncoding=UTF-8
